name: Test

on: push

jobs:
  test:
    runs-on: homebrew/brew

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew bundle

    - name: Run tests
      run: |
        make test
