name: Test

on: push

env:
  KUSTOOL_ROOT: '/home/runner/work/kustool/kustool'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3.5.0

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        echo PATH $PATH
        mkdir vendor
        touch vendor/modules.txt
        export PATH=$PATH:$(go env GOPATH)/bin

        sudo apt-get update
        sudo apt-get install -y bats golang curl

        curl https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 > /usr/local/bin/yq

        go install github.com/josephburnett/jd@latest

        yq --version
        jd --version
        bats --version

        yq --help

    - name: Run tests
      shell: bash
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin

        make test
